// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4-0saoRap5Kv3lr8D6Rpi4aAxYaNP6X0',
    appId: '1:800913624553:web:a2275224713271ec17cf78',
    messagingSenderId: '800913624553',
    projectId: 'ortaksepet',
    authDomain: 'ortaksepet.firebaseapp.com',
    storageBucket: 'ortaksepet.firebasestorage.app',
    measurementId: 'G-0XETD26XNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3sePTEO5t_j05kz8LbkY_v-xANWh8Mg',
    appId: '1:800913624553:android:cf6a01666ea9df7b17cf78',
    messagingSenderId: '800913624553',
    projectId: 'ortaksepet',
    storageBucket: 'ortaksepet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuDlRMW90Kfwu1QhHOlheyIuj_q_-0BhE',
    appId: '1:800913624553:ios:4e3475d2d187e9c817cf78',
    messagingSenderId: '800913624553',
    projectId: 'ortaksepet',
    storageBucket: 'ortaksepet.firebasestorage.app',
    iosBundleId: 'com.example.sepetMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuDlRMW90Kfwu1QhHOlheyIuj_q_-0BhE',
    appId: '1:800913624553:ios:4e3475d2d187e9c817cf78',
    messagingSenderId: '800913624553',
    projectId: 'ortaksepet',
    storageBucket: 'ortaksepet.firebasestorage.app',
    iosBundleId: 'com.example.sepetMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4-0saoRap5Kv3lr8D6Rpi4aAxYaNP6X0',
    appId: '1:800913624553:web:5238d848622acbb617cf78',
    messagingSenderId: '800913624553',
    projectId: 'ortaksepet',
    authDomain: 'ortaksepet.firebaseapp.com',
    storageBucket: 'ortaksepet.firebasestorage.app',
    measurementId: 'G-QRPLM2CJKZ',
  );

}